# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='dob',
            field=models.DateField(default='1984-01-01'),
            preserve_default=False,
        ),
    ]
